#!/usr/bin/env bash
set -euo pipefail

# Generated by Gires CI/CD Tools
# Sync local -> prod
# Usage:
# SYNC_HOST={{SYNC_HOST}} SYNC_USER={{SYNC_USER}} SYNC_PATH={{SYNC_PATH}} \
# DB_NAME={{DB_NAME}} DB_USER={{DB_USER}} DB_PASS={{DB_PASS}} DB_HOST={{DB_HOST}} \
# ./scripts/sync_push.sh <dump.sql>

: "${SYNC_HOST:?Missing SYNC_HOST}"
: "${SYNC_USER:?Missing SYNC_USER}"
: "${SYNC_PATH:?Missing SYNC_PATH}"
: "${DB_NAME:?Missing DB_NAME}"
: "${DB_USER:?Missing DB_USER}"
: "${DB_PASS:?Missing DB_PASS}"
: "${DB_HOST:=localhost}"

DUMP_FILE="${1:-}"
if [ -z "$DUMP_FILE" ] || [ ! -f "$DUMP_FILE" ]; then
  echo "Usage: ./scripts/sync_push.sh <dump.sql>"
  exit 1
fi

REMOTE_DB_DUMP="/tmp/wp_db_push.sql"

scp "$DUMP_FILE" "${SYNC_USER}@${SYNC_HOST}:${REMOTE_DB_DUMP}"
ssh "${SYNC_USER}@${SYNC_HOST}" "MYSQL_PWD='${DB_PASS}' /usr/bin/mysql -h ${DB_HOST} -u ${DB_USER} ${DB_NAME} < ${REMOTE_DB_DUMP}"
ssh "${SYNC_USER}@${SYNC_HOST}" "rm -f ${REMOTE_DB_DUMP}"

rsync -avz --delete "wp-content/uploads/" "${SYNC_USER}@${SYNC_HOST}:${SYNC_PATH}/wp-content/uploads/"

echo "OK: DB + uploads pushed."
