#!/usr/bin/env bash
set -euo pipefail

# Generated by Gires CI/CD Tools
# Sync prod -> local
# Usage:
# SYNC_HOST={{SYNC_HOST}} SYNC_USER={{SYNC_USER}} SYNC_PATH={{SYNC_PATH}} \
# DB_NAME={{DB_NAME}} DB_USER={{DB_USER}} DB_PASS={{DB_PASS}} DB_HOST={{DB_HOST}} \
# ./scripts/sync_pull.sh

: "${SYNC_HOST:?Missing SYNC_HOST}"
: "${SYNC_USER:?Missing SYNC_USER}"
: "${SYNC_PATH:?Missing SYNC_PATH}"
: "${DB_NAME:?Missing DB_NAME}"
: "${DB_USER:?Missing DB_USER}"
: "${DB_PASS:?Missing DB_PASS}"
: "${DB_HOST:=localhost}"

TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BACKUP_DIR="backups"
mkdir -p "$BACKUP_DIR"

REMOTE_DB_DUMP="/tmp/wp_db_${TIMESTAMP}.sql"
LOCAL_DB_DUMP="$BACKUP_DIR/wp_db_${TIMESTAMP}.sql"

ssh "${SYNC_USER}@${SYNC_HOST}" "MYSQL_PWD='${DB_PASS}' /usr/bin/mysqldump -h ${DB_HOST} -u ${DB_USER} ${DB_NAME} > ${REMOTE_DB_DUMP}"
scp "${SYNC_USER}@${SYNC_HOST}:${REMOTE_DB_DUMP}" "$LOCAL_DB_DUMP"
ssh "${SYNC_USER}@${SYNC_HOST}" "rm -f ${REMOTE_DB_DUMP}"

rsync -avz --delete "${SYNC_USER}@${SYNC_HOST}:${SYNC_PATH}/wp-content/uploads/" "wp-content/uploads/"

echo "OK: DB + uploads pulled."
