<?php

namespace GiresCICD;

class Scripts {
    private $settings;

    public function __construct(Settings $settings) {
        $this->settings = $settings;
    }

    public function generate($include_secrets = false, $allow_defaults = true) {
        $settings = $allow_defaults ? $this->settings->get_all() : [];

        $vars = [
            'SYNC_HOST' => $settings['ssh_host'] ?? 'ssh.host.tld',
            'SYNC_USER' => $settings['ssh_user'] ?? 'user',
            'SYNC_PATH' => $settings['ssh_path'] ?? '/path/to/wp',
            'DB_NAME' => $settings['db_name'] ?? 'db_name',
            'DB_USER' => $settings['db_user'] ?? 'db_user',
            'DB_PASS' => $settings['db_pass'] ?? 'db_pass',
            'DB_HOST' => $settings['db_host'] ?? 'localhost',
            'RSYNC_EXCLUDES' => $this->build_rsync_excludes($settings['rsync_excludes'] ?? ''),
        ];

        if (!$include_secrets) {
            $vars['DB_PASS'] = 'CHANGE_ME';
        }

        $scripts_dir = ABSPATH . 'scripts';
        if (!is_dir($scripts_dir)) {
            wp_mkdir_p($scripts_dir);
        }
        if (!is_dir($scripts_dir) || !is_writable($scripts_dir)) {
            return false;
        }

        $pull = file_get_contents(GIRES_CICD_DIR . 'templates/sync_pull.sh.tpl');
        $push = file_get_contents(GIRES_CICD_DIR . 'templates/sync_push.sh.tpl');

        if (!$pull || !$push) {
            return false;
        }

        foreach ($vars as $key => $value) {
            $pull = str_replace('{{' . $key . '}}', $value, $pull);
            $push = str_replace('{{' . $key . '}}', $value, $push);
        }

        file_put_contents($scripts_dir . '/sync_pull.sh', $pull);
        file_put_contents($scripts_dir . '/sync_push.sh', $push);

        @chmod($scripts_dir . '/sync_pull.sh', 0755);
        @chmod($scripts_dir . '/sync_push.sh', 0755);

        return true;
    }

    private function build_rsync_excludes($raw) {
        $lines = preg_split('/\r?\n/', (string) $raw);
        $lines = array_values(array_filter(array_map('trim', $lines)));
        if (empty($lines)) {
            return '';
        }
        $parts = [];
        foreach ($lines as $line) {
            $parts[] = '--exclude=' . escapeshellarg($line);
        }
        return implode(' ', $parts);
    }

    public static function cleanup() {
        $scripts_dir = ABSPATH . 'scripts';
        $targets = [
            $scripts_dir . '/sync_pull.sh',
            $scripts_dir . '/sync_push.sh',
        ];

        foreach ($targets as $file) {
            if (!is_file($file)) {
                continue;
            }
            $content = @file_get_contents($file);
            if ($content !== false && strpos($content, 'Generated by Gires CI/CD Tools') !== false) {
                @unlink($file);
            }
        }
    }
}
